# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'treasure hunter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for treasure hunter
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage' 
  pod 'CryptoSwift'
target 'treasure hunterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'treasure hunterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
